version: '3.8'

services:
    pgdatabase:
        image: postgres:14.2
        container_name: postgres
        hostname: pgdatabase
        volumes:
            - ./postgresql/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: Rashit
            POSTGRES_PASSWORD: aderader
            POSTGRES_DB: TaskTracker
            PGDATA: "/var/lib/postgresql/data"
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U Rashit -d TaskTracker"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

    pg_admin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        depends_on:
            - pgdatabase
        environment:
            PGADMIN_DEFAULT_EMAIL: "7119967@mail.ru"
            PGADMIN_DEFAULT_PASSWORD: "aderader"
            PGADMIN_LISTEN_PORT: 80
        links:
            - "pgdatabase: pgsql-server"
        ports:
            - 5050:80            
            - 5051:443
        restart: unless-stopped

    tasktracker.api:
        image: ${DOCKER_REGISTRY-}tasktrackerapi
        build:
          context: .
          dockerfile: TaskTracker.API/Dockerfile
        ports:
          - 5172:80
          - 443
        depends_on:
          - pgdatabase

    tasktracker.ui:
        image: ${DOCKER_REGISTRY-}tasktrackerui
        build:
            context: .
            dockerfile: TaskTracker.UI/Dockerfile
        ports:
          - 80
          - 443
        depends_on:
          - pgdatabase

    nginx.proxy:
        container_name: nginx.proxy
        image: nginx:latest
        ports:
          - 80:80
          - 443:443
        depends_on:
          - tasktracker.ui
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
   default:
        name: tasktracker-network

volumes:
  pgdata: {}